### ISSUE TITLE
LD error happend when i compile xformers on mi100

### ISSUE THREAD

**Issue by TimeYWL** [ROCmSoftwarePlatform/xformers#12]
# 🐛 Bug
`
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.1.0a0+git413b4cd with CUDA None (you have 2.1.0a0+git413b4cd)
    Python  3.9.18 (you have 3.9.18)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
Traceback (most recent call last):
  File "/data1/ywl/xformers/xformers/_cpp_lib.py", line 121, in _register_extensions
    torch.ops.load_library(ext_specs.origin)
  File "/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/_ops.py", line 787, in load_library
    ctypes.CDLL(path)
  File "/opt/conda/envs/py_3.9/lib/python3.9/ctypes/__init__.py", line 383, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /data1/ywl/xformers/xformers/_C.so: undefined symbol: _ZN2at4cuda6philox6unpackENS_15PhiloxCudaStateE
`

After I compiled xformers by `python setup.py bdist_wheel`, it shows when I run `python -m xformers.info`.
Is there any reason caused this？
## To Reproduce

1.
2.
3.

## Environment

Please copy and paste the output from the
environment collection script from PyTorch
(or fill out the checklist below manually).

You can run the script with:

```bash
# For security purposes, please check the contents of collect_env.py before running it.
python -m torch.utils.collect_env
```

- PyTorch Version (e.g., 1.0):
- OS (e.g., Linux):
- How you installed PyTorch (`conda`, `pip`, source):
- Build command you used (if compiling from source):
- Python version:
- CUDA/cuDNN version:
- GPU models and configuration:
- Any other relevant information:

**Comment by tenpercent** [comment]
Hi @TimeYWL!

```
$ c++filt -n _ZN2at4cuda6philox6unpackENS_15PhiloxCudaStateE 
at::cuda::philox::unpack(at::PhiloxCudaState)
```

-- there might be an issue with torch installation. Could you run the script which collects environment (as suggested above) for more context? Also, are you trying to install on bare metal or in a container?
