### ISSUE TITLE
Investigate CK illegal memory access on shape  `(256, 4096, 16, 64)`

### ISSUE THREAD

**Issue by tenpercent** [ROCmSoftwarePlatform/xformers#7]
# 🐛 Bug

Benchmark crashes on input shape `(256, 4096, 16, 64)` with illegal memory access (unknown)

## Command

See #6 for details;

```
python /xformers/xformers/benchmarks/benchmark_mem_eff_attention.py --omit-baselines
```

## To Reproduce

1. Check out the branch in #6 
2. Run the docker image and mount `xformers` and `phantom_amd_llm_operators` projects with `docker run -it --cap-add=SYS_PTRACE --security-opt seccomp=unconfined --device=/dev/kfd --device=/dev/dri --group-add video --ipc=host --shm-size 8G -v $HOME/xformers:/xformers -v $HOME/phantom_amd_llm_operators/:/phantom_amd_llm_operators  rocm/pytorch-nightly:latest`
3. `pip install -e /phantom_amd_llm_operators/third-party/triton/python/`
4. `pip install -e /xformers`
5. `pip install scipy==1.10 matplotlib seaborn pandas`
6. `python /xformers/xformers/benchmarks/benchmark_mem_eff_attention.py --omit-baselines`

## Expected behavior

Benchmark doesn't crash

**Comment by qianfengz** [comment]
This issue seems like an pytorch issue on ROCM.   The following are the tracing information collected by me
```bash
root@dc-gbm-02:/data2/xformers# python xformers/benchmarks/benchmark_mem_eff_attention_ck.py
====== {'shape': (256, 4096, 16, 64), 'num_threads': 1, 'dropout_p': 0.0, 'attn_bias_cfg': (<class 'NoneType'>, False), 'dtype': torch.float16} ======                                                     
optimized: memory used: 2048.0 MB                                                                                                                                                                          
Traceback (most recent call last):                                                                                                                                                                         
  File "xformers/benchmarks/benchmark_mem_eff_attention_ck.py", line 302, in <module>
    main()
  File "xformers/benchmarks/benchmark_mem_eff_attention_ck.py", line 297, in main
    benchmark_main_helper(mem_eff_attention_fw, CASES, min_run_time=min_run_time)
  File "/data2/xformers/xformers/benchmarks/utils.py", line 436, in benchmark_main_helper
    benchmark_run_and_compare(
  File "/data2/xformers/xformers/benchmarks/utils.py", line 606, in benchmark_run_and_compare
    measurement = benchmark_object.blocked_autorange(
  File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/utils/benchmark/utils/timer.py", line 372, in blocked_autorange
    number = self._estimate_block_size(min_run_time)
  File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/utils/benchmark/utils/timer.py", line 319, in _estimate_block_size
    time_taken = self._timeit(number)
  File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/utils/benchmark/utils/timer.py", line 264, in _timeit
    return max(self._timer.timeit(number), 1e-9)
  File "/opt/conda/envs/py_3.8/lib/python3.8/timeit.py", line 177, in timeit
    timing = self.inner(it, self.timer)
  File "<timeit-src>", line 6, in inner
  File "xformers/benchmarks/benchmark_mem_eff_attention_ck.py", line 53, in ref_attention
    out = ref_attention_bmk(T(q), T(k), T(v), attn_bias, p)
  File "xformers/benchmarks/benchmark_mem_eff_attention_ck.py", line 31, in ref_attention_bmk
    attn = q @ k.transpose(-2, -1)
torch.cuda.OutOfMemoryError: HIP out of memory. Tried to allocate 128.00 GiB. GPU 0 has a total capacity of 63.98 GiB of which 43.68 GiB is free. Of the allocated memory 20.00 GiB is allocated by PyTorch, and 0 bytes is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_HIP_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
```
The issue is also the reason that I disabled many cases with big sizes in `benchmark_mem_eff_attention_ck.py`
